[project]
name = "pattern_service"
version = "0.1.0"
description = "Pattern Service Django project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "Django>=5.0,<6.0",
    "djangorestframework>=3.16.0,<3.17"
]

[tool.black]
line-length = 160
fast = true
skip-string-normalization = true

[tool.isort]
profile = "black"
force_single_line = true
line_length = 120

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["pattern_service"]
