---
name: Linters

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - stable-*
    tags:
      - "*"

jobs:
  linters:
    name: Linters
    uses: ansible-network/github_actions/.github/workflows/tox.yml@main
    with:
      envname: linters
